name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
      - id: get-version
        run: echo "name=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          commit: ${{ github.sha }}
          name: ${{ steps.get-version.outputs.version }}
